pipeline {
    agent any

    environment {
        IMAGE_NAME = 'app-generator:latest'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'master',
                    url: 'https://github.com/app-generator/app-generator.git'
            }
        }

        stage('Lint & Static Analysis') {
            steps {
                sh '''
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install --upgrade pip
                    pip install flake8
                    [ -f requirements.txt ] && pip install -r requirements.txt || echo "No requirements.txt found"
                    flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
                '''
            }
        }

        stage('Execute Tests') {
            steps {
                sh '''
                    . venv/bin/activate
                    pip install pytest
                    pytest
                '''
            }
        }

        stage('Build Docker Image') {
            steps {
                sh """
                    docker build -t ${IMAGE_NAME} .
                """
            }
        }
    }

     post {

        always {
            echo 'Cleaning workspace and Docker artifacts...'
            cleanWs()
            sh """
                docker rmi -f ${IMAGE_NAME} || true
            """
        }

        success {
            echo 'Pipeline succeeded!'
        }

        failure {
            echo 'Pipeline Filed!'
        }
    }
}




